# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def swift_pods
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Moya', '~> 15.0'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'R.swift'
  pod 'Alamofire', '~> 5.0.0'#网络请求
end

target 'HHObjectiveCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HHSwift
  swift_pods
  # Pods for HHObjectiveCDemo
  pod 'ReactiveObjC', '3.1.1'
  pod 'Masonry', '1.1.0'
  pod 'XMPPFramework', '4.0.0'
  pod 'MJRefresh', '3.7.5'
  pod 'MBProgressHUD', '1.2.0'
  pod 'SDWebImage', '5.12.3' # 网络图片处理框架
  #pod 'SDWebImage/GIF' # 网络动图处理
  pod 'HJCornerRadius', :git => 'https://github.com/panghaijiao/HJCornerRadius.git'
  pod 'AliyunOSSiOS', '2.10.12' # 阿里云对象存储
  pod 'AliyunSlsObjc', '1.2.0' # 阿里云日志
  pod 'JPush', '4.8.0'
  pod 'FMDB'
  # Pods for UM
  pod 'UMCommon' # 友盟基础库
  pod 'UMDevice'
  # 集成微信(完整版14.4M)
  pod 'UMShare/Social/WeChat' # 微信分享(完整版)
  pod 'PLCrashReporter', '1.11.1' #crash日志收集
  #pod 'WechatOpenSDK'#微信开放平台

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#    end
#  end
#end
